### PR TITLE
ENH: Add ensemble estimators to pipelines

### PR DESCRIPTION
**Pull request by richford**
This PR adds bagging and AdaBoost ensemble meta-estimators to the AFQ pipelines.

### CODE REVIEW

**Review by arokem — COMMENTED** [review]
The code all looks good. Small suggestion/question: Maybe you could allow users to pass an already initialized meta-estimator as another option for the `ensemble_meta_estimator` kwarg?

**Comment by richford** [comment]
Yeah, that would have some nice parallelism with the other options (e.g. scaler, imputer). AFAIK, bagging and adaboost are the only sklearn ensemble estimators that allow you to supply your own base estimator (e.g. SGL). However, the user might want to roll their own, in which case your suggestion would be really useful. I'll add some logic to `make_base_afq_pipeline` that allows this.

**Comment by richford** [comment]
@arokem, I implemented your suggestion in [1a335fd](https://github.com/richford/AFQ-Insight/pull/59/commits/1a335fdc4897415484da8059ec836932f28db782).

**Comment by arokem** [comment]
Looks great! 👍 to merge from my end.

**Pull request merged**
